# Generated by Django 5.2.4 on 2026-05-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_blockedipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='require_anonymous_comment_captcha',
            field=models.BooleanField(default=True, help_text='When enabled, anonymous users must pass image verification to post comments or replies.'),
        ),
    ]
