# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-23 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170405_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='post',
            name='approve_comment',
            field=models.BooleanField(default=False),
        ),
    ]
