# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-30 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170823_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
