# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-07 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
