# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-23 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_comment_comment_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
