# Generated by Django 5.2.4 on 2026-05-06 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_meaninglesscommentattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameIndex(
            model_name='meaninglesscommentattempt',
            new_name='entries_mea_ip_addr_faf761_idx',
            old_name='encm_ip_created',
        ),
        migrations.RenameIndex(
            model_name='meaninglesscommentattempt',
            new_name='entries_mea_created_0aef36_idx',
            old_name='encm_created',
        ),
    ]
